version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
  spring-app:
    build:
      context: ./spring-app
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongodb